

site.host.stable=${project.url}
site.host.stable.desc=PARENT-STABLE
site.host.dev=http://localhost:9000/
site.host.dev.desc=PARENT-DEV
site.host=${site.host.dev}
site.host.other=${site.host.stable}
site.host.other.desc=${site.host.stable.desc}
project.build.sourceEncoding=UTF-8
project.build.directory=deploy
project.webapp.directory=src/main/resources/www/
main.class=systems.symbol.CLI
maven.compiler.plugin.version=3.8.1
maven.compiler.plugin.source=11
maven.compiler.plugin.target=11
winstone.version=1.0.4
spring.version=5.3.10
slf4j.version=1.7.32
sesame.version=2.7.12
camel.version=2.13.1
lucene.version=4.5.0
stanbol.version=0.10.0
james.version=3.0-M2
vaadin.version=7.1.8
restlet.version=2.4.3
handlebars.version=2.0.0
rdf4j.version=3.7.2
groovy.version=3.0.8
groovy-eclipse-compiler.version=3.7.0
groovy-eclipse-batch.version=3.0.8-01 