# Avoid conflict between multiple Quarkus container image extensions during local builds
quarkus.container-image.builder=docker
quarkus.container-image.build=false
quarkus.container-image.push=false
quarkus.container-image.registry=
quarkus.container-image.group=
quarkus.container-image.name=iq-trusted
