SELECT DISTINCT ?this ?label ?definition
WHERE {
    ?this <http://www.w3.org/2004/02/skos/core#prefLabel> ?label .
    OPTIONAL {
        ?this <http://www.w3.org/2004/02/skos/core#definition> ?definition.
    }
}
