quarkus.http.port=8080
quarkus.arc.scan-packages=systems.symbol.realm,systems.symbol.controller.platform,systems.symbol.controller.ux
quarkus.management.endpoints.enabled=true
quarkus.management.endpoints.web.expose=health,metrics,config,env,info,shutdown,beans
quarkus.log.manager=org.jboss.logmanager.LogManager
quarkus.application.ui-header=IQ APIs
quarkus.analytics.disabled=true
quarkus.banner.enabled=false
quarkus.console.enabled=false
iq.realm.jwt.duration=2628288
