quarkus.http.port=8080
quarkus.container-image.name=iq-apis
quarkus.live-reload.instrumentation=true
quarkus.arc.scan-packages=systems.symbol.realm,systems.symbol.controller.platform,systems.symbol.controller.ux
quarkus.management.endpoints.enabled=true
quarkus.management.endpoints.web.expose=health,metrics,config,env,info,shutdown,beans
quarkus.log.manager=org.jboss.logmanager.LogManager
quarkus.native.resources.includes=public/**
quarkus.application.ui-header=IQ APIs
quarkus.analytics.disabled=true
quarkus.banner.enabled=false
quarkus.console.enabled=true
mp.openapi.scan.disable=false
quarkus.smallrye-openapi.enable=true
quarkus.smallrye-openapi.info-title=IQ API
%dev.quarkus.smallrye-openapi.info-title=IQ API (development)
%test.quarkus.smallrye-openapi.info-title=IQ API (test)
quarkus.smallrye-openapi.info-version=1.0.1
quarkus.smallrye-openapi.info-description=OpenAPI for IQ
quarkus.smallrye-openapi.info-terms-of-service=https://smarttrust.ai/about/ts_and_cs
quarkus.smallrye-openapi.info-contact-email=support@smarttrust.ai
quarkus.smallrye-openapi.info-contact-name=IQ API Support
quarkus.smallrye-openapi.info-contact-url=https://smarttrust.ai/contact
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html

iq.realm.token.duration=120
