package systems.symbol.llm;

/**
 * Interface defining the configuration options for a Language Model (LLM).
 * Provides access to various settings such as URL, name, penalties, and parameters for text generation.
 */
public interface I_LLMConfig {

/**
 * Retrieves the URL of the Language Model.
 *
 * @return The URL of the Language Model.
 */
String getURL();

/**
 * Retrieves the name of the Language Model.
 *
 * @return The name of the Language Model.
 */
String getName();


/**
 * Retrieves the response type.
 *
 * @return The response type.
 */
String getResponseFormat();


String getSecretName();

/**
 * Retrieves the frequency penalty applied during text generation.
 * Higher values penalize frequent tokens, encouraging diversity in generated text.
 *
 * @return The frequency penalty.
 */
float getFrequencyPenalty();

/**
 * Retrieves the temperature setting for controlling the randomness of text generation.
 * Higher values increase randomness, resulting in more creative but less coherent text.
 *
 * @return The temperature setting.
 */
float getTemperature();

/**
 * Retrieves the maximum number of tokens allowed in the generated text.
 * Limits the length of the generated text to prevent overly long outputs.
 *
 * @return The maximum number of tokens.
 */
int getMaxTokens();

/**
 * Retrieves the top-p (nucleus) sampling threshold for text generation.
 * Controls the diversity of generated text by filtering out low-probability tokens.
 *
 * @return The top-p threshold.
 */
float getTopP();

/**
 * Retrieves the number of text samples generated by the Language Model.
 * Determines the quantity of text produced in a single generation request.
 *
 * @return The number of text samples.
 */
int getN();

/**
 * Retrieves the seed value used for randomization during text generation.
 * Provides reproducibility by ensuring consistent generation results with the same seed.
 *
 * @return The seed value.
 */
int getSeed();
}
