SELECT DISTINCT ?id ?label ?comment ?content ?image ?url
WHERE {
    ?id rdfs:label ?label.
    OPTIONAL {
        ?id rdfs:comment ?comment.
    }
    OPTIONAL {
        ?id iq:image ?image.
    }
    OPTIONAL {
        ?id iq:url ?url.
    }
    OPTIONAL {
        ?id rdf:value ?content.
    }
}
