PREFIX QRX: <QRX:>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
CONSTRUCT {
?s ?p ?o .
}
WHERE {
{
?p rdfs:isDefinedBy QRX:Ontology .
?s ?p ?o .
} UNION {
?s ?p ?o .
FILTER(?p = rdf:type )
}
}
