SELECT DISTINCT ?id ?label ?content ?definition ?score
WHERE {
    ?id my:label ?label.
    OPTIONAL {
        ?id rdfs:comment ?comment.
    }
    OPTIONAL {
        ?id rdf:value ?content.
    }
    VALUES (?id ?score) { {{{these}}} }
}
