prefix iq: <iq:>
prefix : <iq:test:>

CONSTRUCT {
    ?agent iq:current ?current.
    ?agent iq:initial ?initial.
    ?current iq:to ?next.
    ?next rdfs:label ?label.
    ?current rdfs:label ?current_label.
    ?agent rdfs:label ?agent_label.
} WHERE {
    ?agent a iq:Agent;
        iq:initial ?initial;
        iq:current ?current.
    ?current iq:to+ ?next.
    ?next rdfs:label ?label.
    ?current rdfs:label ?current_label.
    ?agent rdfs:label ?agent_label.
}