name: Build IQ Jars

on:
  push:
branches:
  - main

jobs:
  build:
runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v3

  # Install Git LFS
  - name: Install Git LFS
run: |
  sudo apt-get update
  sudo apt-get install git-lfs
  git lfs install
  
  # Pull the LFS files (like large model files)
  - name: Pull LFS files
run: git lfs pull

  - name: JDK 21
uses: actions/setup-java@v3
with:
  java-version: '21'
  distribution: 'adopt'
  
  # Build Maven package
  - name: Build Maven package
run: mvn --batch-mode --update-snapshots package -Dquarkus.container-image.build=false -Dquarkus.container-image.push=false -DskipITs
  # Publish to GitHub packages
  - name: Publish to GitHub packages
run: mvn --batch-mode deploy
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
